// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpC93kTTEwDglefBhlkYl3WoeJpvYhDX4',
    appId: '1:1031618891728:web:3f3657ba6fbd982032b3d5',
    messagingSenderId: '1031618891728',
    projectId: 'baby-checklist-app',
    authDomain: 'baby-checklist-app.firebaseapp.com',
    storageBucket: 'baby-checklist-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQeKhLUhwsYcIfvTaftGXJt-h5n14qb-c',
    appId: '1:1031618891728:android:029f3765de7aaa8232b3d5',
    messagingSenderId: '1031618891728',
    projectId: 'baby-checklist-app',
    storageBucket: 'baby-checklist-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXPtjmC7LUPuWpSsAmwOR5yE18NdBYJQc',
    appId: '1:1031618891728:ios:928ae58782c56a8a32b3d5',
    messagingSenderId: '1031618891728',
    projectId: 'baby-checklist-app',
    storageBucket: 'baby-checklist-app.firebasestorage.app',
    iosBundleId: 'com.example.apdpApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXPtjmC7LUPuWpSsAmwOR5yE18NdBYJQc',
    appId: '1:1031618891728:ios:928ae58782c56a8a32b3d5',
    messagingSenderId: '1031618891728',
    projectId: 'baby-checklist-app',
    storageBucket: 'baby-checklist-app.firebasestorage.app',
    iosBundleId: 'com.example.apdpApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpC93kTTEwDglefBhlkYl3WoeJpvYhDX4',
    appId: '1:1031618891728:web:22a45e3f70ca358532b3d5',
    messagingSenderId: '1031618891728',
    projectId: 'baby-checklist-app',
    authDomain: 'baby-checklist-app.firebaseapp.com',
    storageBucket: 'baby-checklist-app.firebasestorage.app',
  );
}
